import { Router, Request, Response } from 'express';
import { apiKeyAuth } from '../middleware/auth';
import { config } from '../config';
import { IamTokenManager } from 'ibm-cloud-sdk-core';
import { createSalesforceOpportunity } from '../integrations/salesforce';

const router = Router();

// Configure the IAM Token Manager for Orchestrate API
const tokenManager = new IamTokenManager({
  apikey: config.orchestrateApiKey,
});

function extractStubFromHistory(history: Array<{ role: string; content: string }>, context: string): any {
  const combined = [context, ...history.map(h => h.content)].reverse().join('\n');

  let accountName = 'Customer Account';
  let opportunityName = 'IBM Pre-Sales Opportunity';
  let stage = 'Qualification';
  let estimatedValue = '$150,000 USD';
  let notes = 'Pre-sales opportunity generated by Partner Growth Copilot.';

  const accountMatch = combined.match(/(?:Account\s*Name|Customer\s*Name|Account):\s*([^\n;]+)/i);
  if (accountMatch) accountName = accountMatch[1].replace(/[*_#]/g, '').trim();

  const oppMatch = combined.match(/(?:Opportunity\s*Name|Solution\s*Name|Solution):\s*([^\n;]+)/i);
  if (oppMatch) opportunityName = oppMatch[1].replace(/[*_#]/g, '').trim();

  const valueMatch = combined.match(/(?:Estimated\s*Value|Contract\s*Value|Budget|Value):\s*([^\n;]+)/i);
  if (valueMatch) estimatedValue = valueMatch[1].replace(/[*_#]/g, '').trim();

  const notesMatch = combined.match(/(?:Notes|Summary|Use\s*case):\s*([^\n;]+)/i);
  if (notesMatch) notes = notesMatch[1].replace(/[*_#]/g, '').trim();

  return {
    account_name: accountName,
    opportunity_name: opportunityName,
    stage,
    estimated_value: estimatedValue,
    notes,
  };
}

router.get('/api/chat-service', (req: Request, res: Response): void => {
  res.json({ status: 'online', mode: 'orchestrate-proxy', agent: config.orchestrateAgentId });
});

router.post('/api/chat', apiKeyAuth, async (req: Request, res: Response): Promise<void> => {
  const { message, history = [], conversation_context = '', thread_id = 'default-thread', crm_stub } = req.body || {};

  if (!message || typeof message !== 'string' || !message.trim()) {
    res.status(400).json({ error: 'Bad Request', message: 'message is required.' });
    return;
  }

  // Route Salesforce push triggers directly
  const isSalesforceTrigger = /push\s+(?:this\s+)?to\s+salesforce|create\s+(?:this\s+)?in\s+salesforce|log\s+(?:this\s+)?(?:opportunity\s+)?(?:in\s+|to\s+)?salesforce|sync\s+(?:to\s+)?salesforce/i.test(message);
  if (isSalesforceTrigger) {
    try {
      const stub = crm_stub || extractStubFromHistory(history, conversation_context);
      const sfResult = await createSalesforceOpportunity(stub);
      res.json({
        role: 'assistant',
        type: 'salesforce_sync',
        intent: 'push_to_salesforce',
        success: true,
        salesforce_opportunity_id: sfResult.salesforce_opportunity_id,
        salesforce_url: sfResult.salesforce_url,
        content: `✅ **Successfully created Opportunity in Salesforce!**\n\n- **Salesforce Record ID:** \`${sfResult.salesforce_opportunity_id}\`\n- **Opportunity Name:** ${sfResult.opportunity_name}\n- **Account:** ${sfResult.account_name}\n- **Stage:** ${sfResult.stage}\n- **Close Date:** ${sfResult.close_date}\n\n🔗 **[View Opportunity in Salesforce](${sfResult.salesforce_url})**`,
        assistant_message: sfResult.display_message,
        salesforce_data: sfResult,
      });
      return;
    } catch (err: any) {
      console.error('[Chat Salesforce Trigger Error]', err);
      res.json({
        role: 'assistant',
        type: 'salesforce_sync',
        intent: 'push_to_salesforce',
        success: false,
        content: `❌ **Failed to push to Salesforce:** ${err?.message || 'Unknown error'}`,
        assistant_message: `Salesforce sync failed: ${err?.message || 'Unknown error'}`,
      });
      return;
    }
  }

  try {
    const token = await tokenManager.getToken();
    
    // Construct the Orchestrate endpoint based on common Watsonx API patterns
    const baseUrl = config.orchestrateHostUrl.replace(/\/$/, '');
    const agentId = config.orchestrateAgentId;
    
    // Some WxO environments use /v1/orchestrate/{agentId}/chat/completions or similar. 
    // Adjust path if your deployment differs.
    const orchestrateUrl = `${baseUrl}/v1/orchestrate/${agentId}/chat/completions`;

    const messages = [];
    
    messages.push({
      role: 'system',
      content: `IMPORTANT: Do NOT generate ASCII box-and-arrow diagrams for architectures. Instead, describe the architecture as a clean ordered list or a proper markdown table with columns like "Layer | IBM Product | Role". When writing follow-up email drafts, format as **Subject:** <Subject text> followed directly by the email body. Do NOT include "Body (HTML):" or "Email Body:" label headers, and never wrap email text in HTML tags (<p>, <ul>, <li>) or code fences (\`\`\`html). Before generating any clarifying question, first extract all deal details already present in \`history\` (account name, industry, use case, budget, timeline, stakeholders, tech stack). Never re-ask for information already provided. If the user says something like "don't know", "just create it", "skip", or "go ahead", immediately call generate-full-opportunity-package with whatever fields are known and mark any missing ones as "Not specified" rather than asking again.`
    });

    if (conversation_context) {
      messages.push({
        role: 'system',
        content: `Deal Context (previously generated package):\n${conversation_context}`
      });
    }

    const recentHistory = (history as Array<{ role: string; content: string }>).slice(-10);
    console.log(`[Proxy] History items: ${recentHistory.length}`);

    let contextString = '';
    if (recentHistory.length > 0) {
      contextString += `[Previous Conversation History]\n`;
      for (const turn of recentHistory) {
        if (turn.role && turn.content) {
          contextString += `${turn.role.toUpperCase()}: ${turn.content}\n`;
        }
      }
      contextString += `[End of History]\n\n`;
    }

    const finalUserMessage = contextString 
      ? `${contextString}Current User Message:\n${message.trim()}`
      : message.trim();

    messages.push({ role: 'user', content: finalUserMessage });

    console.log(`[Proxy] Sending request to Orchestrate Agent ${agentId}...`);
    
    const response = await fetch(orchestrateUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
        'X-IBM-THREAD-ID': thread_id
      },
      body: JSON.stringify({
        messages,
        stream: false,
        agentEnvironmentId: config.orchestrateEnvironmentId
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error('[Orchestrate API Error]', response.status, errText);
      res.status(response.status).json({ error: 'Orchestrate Agent Error', details: errText });
      return;
    }

    const data = await response.json();
    const rawContent = data.choices?.[0]?.message?.content || '';
    
    console.log('[Proxy] Response received from Orchestrate Agent');

    let parsedPackage = null;
    let isProposal = false;
    let isEmail = false;

    try {
      const jsonMatch = rawContent.match(/```json\s*([\s\S]*?)\s*```/) || rawContent.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const potentialJson = jsonMatch[1] || jsonMatch[0];
        const parsed = JSON.parse(potentialJson);
        if (parsed.proposal || parsed.handoff_summary || parsed.crm_stub || parsed.recommended_ibm_stack) {
          parsedPackage = parsed;
          isProposal = true;
        } else if (parsed.email_body || parsed.subject) {
          parsedPackage = parsed;
          isEmail = true;
        }
      }
    } catch(e) {
    }

    if (!parsedPackage) {
      if (
        rawContent.includes('IBM Solution Proposal') ||
        rawContent.includes('Proposed Architecture') ||
        rawContent.includes('Solution Name:') ||
        rawContent.includes('Recommended IBM Stack') ||
        rawContent.includes('CRM Opportunity Stub') ||
        rawContent.includes('Implementation Roadmap') ||
        rawContent.includes('Proposed IBM Stack')
      ) {
        isProposal = true;
        parsedPackage = {
          proposal: {
            proposal: rawContent
          }
        };
      } else if (rawContent.includes('Subject:') && (rawContent.includes('Dear') || rawContent.includes('Hi'))) {
        isEmail = true;
        parsedPackage = {
          email_body: rawContent
        };
      }
    }

    if (isProposal) {
      res.json({
        role: 'assistant',
        type: 'proposal',
        assistant_message: parsedPackage?.proposal?.proposal || rawContent,
        content: rawContent,
        package_data: parsedPackage,
        intent: 'generate_package'
      });
    } else if (isEmail) {
      res.json({
        role: 'assistant',
        type: 'email',
        assistant_message: rawContent,
        content: rawContent,
        email_data: parsedPackage,
        intent: 'draft_email'
      });
    } else {
      res.json({
        role: 'assistant',
        type: 'followup',
        content: rawContent,
        intent: 'followup'
      });
    }

  } catch (err: any) {
    console.error('[chatRoutes Proxy Error]', err);
    res.status(500).json({ error: 'Proxy failed', message: err.message });
  }
});

export default router;
